# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ffa9c8ef55c9842e4b8ac077564a9fbfbc81c5aa948ee95e7e945021eff366c4d1feb3eac223e3b5e62b2af45b84e4f1cd538016f59abffef5b8015d99a4f50

test:
  secret_key_base: 964bb81de79a27c3d472fe1273413fbde4ee72e536642fac6ebeaf2d8c9c06d048e5c8865027bdbeee1769ae00f4cacf3e4a1450d0dc84ffe3d2d63b7fa5d538

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
